---
version: '2'

networks:
  kafka:
    name: kafka
  scrape:
    name: scrape

services:

  scrape-agent:
    image: selenium/standalone-chrome:latest
    hostname: scrape-agent
    container_name: scrape-agent
    ports:
      - 4444:4444
    networks:
      - scrape
    volumes:
      - /dev/shm:/dev/shm
  scrape-orchestrator:
    build: 
      dockerfile: ./Dockerfile
    container_name: scrape-orchestrator
    environment:
      - SCRAPE_URL=https://livetiming.tsl-timing.com/231245
    networks:
      - kafka
      - scrape
    depends_on:
      - scrape-agent

